name: fake_process_manager
description: Process Manager for faking processes in tests. Taken from Flutter Tools.
version: 1.0.0
homepage: https://github.com/mmcc007/fake_process_manager

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  process: ^5.0.2
  tool_base: ^2.0.0
  test: ^1.17.2

dev_dependencies:
  pedantic: ^1.7.0
  tool_base_test:

dependency_overrides:
  tool_base:
   git: https://github.com/claudius-kienle/tool_base.git
  tool_base_test:
   git: https://github.com/claudius-kienle/tool_base_test.git
    # path: ../tool_base_test
